CREATE TABLE `order_signal` (
  `TRANSACTION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CTX` varchar(100) NOT NULL,
  `STATUS` varchar(100) NOT NULL,
  `ORDER_NO` varchar(255) NOT NULL,
  `PARTNER_ID` varchar(25) DEFAULT NULL,
  `REQUEST` text,
  `PROCESS_FLAG` varchar(5) DEFAULT NULL,
  `RETRY_COUNT` int(11) DEFAULT NULL,
  `ERROR_MESSAGE` varchar(2048) DEFAULT NULL,
  `CREATED_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `LAST_UPDATED_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`TRANSACTION_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
